services:
  website:
    build:
      context: .
      dockerfile: apps/website/Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - /app/node_modules
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
