services:
  website:
    build:
      context: .
      dockerfile: apps/website/Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - 4200:4200
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - 4000:4000
